### PR TITLE
Fix #106, switching Mixpanel instances on iOS

### LINKED ISSUE #106: Changing instance token?
I have some code where I want to change the mixpanel project depending on some factors. I run "Mixpanel.sharedInstanceWithToken(NEW_TOKEN)" but this does not result in the metrics going to the new project.

Is this a restriction on the library or am I attempting this incorrectly?

### PR DESCRIPTION
**Pull request by dloehr**

### CODE REVIEW

File: RNMixpanel/RNMixpanel.m [hunk 1]
```diff
@@ -23,8 +23,7 @@ @implementation RNMixpanel
 
 // sharedInstanceWithToken
 RCT_EXPORT_METHOD(sharedInstanceWithToken:(NSString *)apiToken) {
-    [Mixpanel sharedInstanceWithToken:apiToken];
```
Comment (dloehr) [inline RNMixpanel/RNMixpanel.m]: In Mixpanel's iOS library, [```sharedInstaneWithToken```](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L38) creates an instance, stores it in a dictionary of ```instances```, and returns the instance.

Their [````sharedInstance``` method](https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L58) just returns the instance that was created first.
